include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_use_package_imports
    - always_declare_return_types
    - avoid_print
    - avoid_types_on_closure_parameters
    - avoid_void_async
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - flutter_style_todos
    - package_api_docs
    - prefer_single_quotes
    - test_types_in_equals
    - throw_in_finally
    - unawaited_futures
    - unnecessary_statements
    - unsafe_html
    - use_super_parameters
